common: &common
  session_key: _sid
  session_secret: Ng4CINK9QzoiUtinOLjHnGPQOHyDdkDz

  application_id: 0
  application_name: test
  application_domain: base.test.cyworks.jp
  application_ad_id: DUMMY_AD_ID
  application_mobile_ad_id: DUMMY_AD_ID
  application_top: /test
  application_mobile_top: /test
  
  author: CYWORKS
  author_email: developer@cyworks.jp
  
  mixi_domain: mixi.jp
  mixi_mobile_domain: ma.mixi.net
  
  api_endpoint: http://api.mixi-platform.com/os/0.8
  consumer_key: <consumer_key>
  consumer_secret: <consumer_secret>
  
  oauth_public_key: |
    -----BEGIN CERTIFICATE-----
    MIICDDCCAXWgAwIBAgIJAJ4W4bqTjEGSMA0GCSqGSIb3DQEBBQUAMA8xDTALBgNV
    BAMTBG9zZGUwHhcNMDkwMTA3MDg1MTEwWhcNMTAwMTA3MDg1MTEwWjAPMQ0wCwYD
    VQQDEwRvc2RlMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDAv7N2y4S1TWgL
    1UlaqivxGKyskl5o5TLoZdli2AMHidjVzTJsGX1ydYWJmteicnVLTo//JrmkB19C
    L+IYCOnxo6H5YdNAi+t7e3NRpMJF6YBCV+MXnP2dZx02SHAhO6z4i8P/EMcnNX6l
    sX7cXeMnmYS+X7AG+AS6zVVdSKQwVwIDAQABo3AwbjAdBgNVHQ4EFgQUbONO5jjA
    q8gC34J+iUfAnkZVelswPwYDVR0jBDgwNoAUbONO5jjAq8gC34J+iUfAnkZVeluh
    E6QRMA8xDTALBgNVBAMTBG9zZGWCCQCeFuG6k4xBkjAMBgNVHRMEBTADAQH/MA0G
    CSqGSIb3DQEBBQUAA4GBABzjqyU0s8Kn73dmiK1wh2OgoSGVcHKr8ELHg7pf4J9S
    fkg+OFTYajJhS1lDi3uyMTM486oxi1QxUY7f/c/iDnq09eV914ZEhMhalhD+H9WC
    WThZt1a1SCmWx1Ne2a5O6qeQPtFPSL/BEe6xFWE+0RHYWEK+JcDRhv5MDW0DrJjT
    -----END CERTIFICATE-----
  
  development: false
  pc_available: true
  mobile_available: true

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
